# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    input_sync: true
    default_config: main_config
    configs:
        main_config:
            allowedContent: true
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            styleSet: 'custom_style'
            toolbar:
                - { name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] }
                - { name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ] }
                - '/'
                - { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'CopyFormatting', 'RemoveFormat' ] }
                - { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] }
                - { name: 'insert', items: [ 'Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ] }
                - { name: 'colors', items: [ 'TextColor', 'BGColor' ] }
                - '/'
                - { name: 'clipboard', items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] }
                - { name: 'editing', items: [ 'Find', 'Replace', '-', 'Scayt' ] }
                - { name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] }
                - { name: 'document', items: [ '-', 'Save', 'ExportPdf', 'Preview', '-', 'Source' ] }
